# Nome da aplicação
spring.application.name=backend

# Ativa o perfil 'local' por padrão durante o desenvolvimento
# Isso faz o Spring ler o arquivo application-local.properties automaticamente
spring.profiles.active=local

# -------------------------------------------------------------
# CONFIGURAÇÃO DO FLYWAY (MIGRAÇÕES DE BANCO DE DADOS)
# -------------------------------------------------------------
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# -------------------------------------------------------------
# CONFIGURAÇÃO DO JPA / HIBERNATE
# -------------------------------------------------------------
# 'validate': apenas checa se as entidades Java condizem com as tabelas do Flyway
spring.jpa.hibernate.ddl-auto=validate

# Exibe e formata os comandos SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true